"""add_raid_ended_at_and_cooldown

Revision ID: 0f6850d66db4
Revises: e27f92e793af
Create Date: 2026-04-25 17:17:50.798655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6850d66db4'
down_revision: Union[str, Sequence[str], None] = 'e27f92e793af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raids', sa.Column('ended_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raids', 'ended_at')
    # ### end Alembic commands ###
