"""add_achievements_table

Revision ID: a1b2c3d4e5f6
Revises: 8705d827fc13
Create Date: 2026-04-10 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, Sequence[str], None] = "8705d827fc13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievement_unlocks",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("achievement_id", sa.String(), nullable=False),
        sa.Column("unlocked_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["guild_id", "user_id"], ["users.guild_id", "users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("guild_id", "user_id", "achievement_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("achievement_unlocks")
    # ### end Alembic commands ###
