"""add_lifetime_stats_columns

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-04-11 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c3d4e5f6a7"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("total_rolls", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("users", sa.Column("total_claims", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("users", sa.Column("total_farmer_trades", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("users", sa.Column("total_cleric_trades", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("users", sa.Column("total_emeralds_gained", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "total_emeralds_gained")
    op.drop_column("users", "total_cleric_trades")
    op.drop_column("users", "total_farmer_trades")
    op.drop_column("users", "total_claims")
    op.drop_column("users", "total_rolls")
    # ### end Alembic commands ###
