"""add_raid_tables

Revision ID: dac6c57ab066
Revises: 4d4000e0934f
Create Date: 2026-04-25 16:37:42.572389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac6c57ab066'
down_revision: Union[str, Sequence[str], None] = '4d4000e0934f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raids',
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('spawned_at', sa.Integer(), nullable=False),
        sa.Column('boss_id', sa.String(), nullable=False),
        sa.Column('current_phase', sa.Integer(), nullable=False, default=1),
        sa.Column('target_tag', sa.String(), nullable=True),
        sa.Column('current_power', sa.Integer(), nullable=False, default=0),
        sa.Column('target_power', sa.Integer(), nullable=False),
        sa.Column('ended_at', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.PrimaryKeyConstraint('guild_id', 'spawned_at')
    )
    op.create_table('raid_contributions',
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('spawned_at', sa.Integer(), nullable=False),
        sa.Column('total_power_donated', sa.Integer(), nullable=False, default=0),
        sa.Column('mobs_donated_this_phase', sa.Integer(), nullable=False, default=0),
        sa.Column('is_claimed', sa.Boolean(), nullable=False, default=False),
        sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['users.guild_id', 'users.user_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['guild_id', 'spawned_at'], ['raids.guild_id', 'raids.spawned_at'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('guild_id', 'user_id', 'spawned_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raid_contributions')
    op.drop_table('raids')
    # ### end Alembic commands ###
